### PR TITLE
Use Application Default Credentials.

### PR DESCRIPTION
**Pull request by tmatsuo**
One question: what is the correct way to install python api client library for App Engine?

By the instructions at:
https://developers.google.com/api-client-library/python/start/installation
you can only install 1.2 or older version. I need the latest one.

### CODE REVIEW

**Comment by tmatsuo** [comment]
anthmgoogle@ can you take a look?

**Comment by anthmgoogle** [comment]
Takashi, can you clarify what you want me to look at?

**Comment by tmatsuo** [comment]
Yup, sorry about missing description. This is a change w.r.t the Application Default Credentials.
So if the code looks as you expected, that's fine.

**Comment by amygdala** [comment]
I am not up to speed on the new credentials lib yet, but this looks fine to me.  Does the GoogleCredentials lib use the GOOGLE_APPLICATION_CREDENTIALS env var, or where is that used?

**Comment by tmatsuo** [comment]
Yes, here is the doc:
https://developers.google.com/accounts/docs/application-default-credentials

**Comment by tmatsuo** [comment]
Amy, I separated this PR into 2 parts. One is this, use Application Default Credentials with cmdline-pull. Other PR is applying it to appengine-push.

**Comment by briandorsey** [comment]
LGTM

(with the caveat that I'm not super familiar the Default Credentials pieces.)

**Comment by tmatsuo** [comment]
Thx, merging.

**Pull request merged**
